### ISSUE TITLE
pygame issue

### ISSUE THREAD

**Issue by tarouk2020** [earwig/mwparserfromhell#171]
when trying to install the pygame package always have this error message : 
C:\Program Files\Python35-32\Scripts>pip3 install pygame-1.9.2-cp35-cp35m-win32.whl
Processing c:\program files\python35-32\scripts\pygame-1.9.2-cp35-cp35m-win32.whl
Installing collected packages: pygame
Exception:
Traceback (most recent call last):
  File "c:\program files\python35-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python35-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python35-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python35-32\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "c:\program files\python35-32\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "c:\program files\python35-32\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "c:\program files\python35-32\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "c:\program files\python35-32\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\program files\python35-32\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'c:\\program files\\python35-32\\Lib\\site-packages\\pygame'

I've tried too many methods but all failed

**Comment by Abbe98** [comment]
I believe you are looking for the pygame issue tracker: https://bitbucket.org/pygame/pygame/issues

**Comment by earwig** [comment]
Yeah... I'm not sure how you got here, but this is for an unrelated project.
