### ISSUE TITLE
Error when attempting to replace or remove content of empty section

### ISSUE THREAD

**Issue by Larivact** [earwig/mwparserfromhell#212]
```python
import mwparserfromhell
code = mwparserfromhell.parse('== test ==')
code.replace(code.get_sections(include_headings=False)[1], 'test')
```

results in
```
Traceback (most recent call last):
  File "demo", line 3, in <module>
    code.replace(code.get_sections(include_headings=False)[1], 'test')
  File "/usr/lib/python3/dist-packages/mwparserfromhell/wikicode.py", line 366, in replace
    context, index = self._do_strong_search(obj, recursive)
  File "/usr/lib/python3/dist-packages/mwparserfromhell/wikicode.py", line 135, in _do_strong_search
    context, ind = self._do_strong_search(obj.get(0), recursive)
  File "/usr/lib/python3/dist-packages/mwparserfromhell/wikicode.py", line 258, in get
    return self.nodes[index]
  File "/usr/lib/python3/dist-packages/mwparserfromhell/smart_list.py", line 284, in __getitem__
    return self._render()[key]
IndexError: list index out of range
```

**Comment by earwig** [comment]
Thanks, the implementation of this function for Wikicode objects seems completely wrong. I'll fix it.
