### ISSUE TITLE
ParseError: C tokenizer exited with non-empty token stack.

### ISSUE THREAD

**Issue by halfak** [earwig/mwparserfromhell#224]
See example script below that demonstrates the issue on a specific revision ID from English Wikipedia. 

```
$ python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mwapi
>>> session = mwapi.Session("https://en.wikipedia.org")
Sending requests with default User-Agent.  Set 'user_agent' on mwapi.Session to quiet this message.
>>> doc = session.get(action="query", prop="revisions", revids=352612341, rvprop=["content"], formatversion=2)
The following query raised warnings: {'action': 'query', 'revids': 352612341, 'format': 'json', 'rvprop': 'content', 'prop': 'revisions', 'formatversion': 2}
	- revisions -- {'warnings': 'Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.'}
	- main -- {'warnings': 'Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.'}
>>> text = doc['query']['pages'][0]['revisions'][0]['content']
>>> text[:50]
"The '''2010 [[National Football League (Ireland)|N"
>>> import mwparserfromhell as mwp
>>> mwp.parse(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/halfak/venv/3.5/lib/python3.5/site-packages/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/home/halfak/venv/3.5/lib/python3.5/site-packages/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
```

**Comment by earwig** [comment]
I don't know what's going on yet, but I've managed to reduce the example to this mess:

```
{{a|'''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1='''a''}}
{{a|1=''a'''}}
{{a|1='''a''}}
{{a|1='''a''a'''a'''}}

{|
|-
|'''a''
|}
```

**Comment by earwig** [comment]
Finally figured it out.
