### ISSUE TITLE
C tokenizer exited with non-empty token stack

### ISSUE THREAD

**Issue by lhoestq** [earwig/mwparserfromhell#247]
Hello ! We have a script that processes wikipedia dumps in [our library](https://github.com/huggingface/nlp/issues/321) but recently we faced an [issue](https://github.com/huggingface/nlp/issues/321) about some contents that  couldn't be parsed correctly. I was able to identify the page that causes the issue and reproduce the error using the content from `mwapi`:
```
Python 3.7.2 (default, Aug 24 2019, 13:20:11) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mwparserfromhell
>>> import mwapi
>>> mwparserfromhell.__version__
'0.5.4'
>>> text = mwapi.Session("https://es.wikipedia.org").get(action='query', prop='revisions', revids=125191022, rvprop=['content'], formatversion=2)['query']['pages'][0]['revisions'][0]['content']
Sending requests with default User-Agent.  Set 'user_agent' on mwapi.Session to quiet this message.
The following query raised warnings: {'action': 'query', 'prop': 'revisions', 'revids': 125191022, 'rvprop': 'content', 'formatversion': 2, 'format': 'json'}
        - main -- {'warnings': 'Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.'}
        - revisions -- {'warnings': 'Because "rvslots" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.'}
>>> mwparserfromhell.parse(text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/quentinlhoest/.virtualenvs/hf-transformers/lib/python3.7/site-packages/mwparserfromhell/utils.py", line 58, in parse_anything
    return Parser().parse(value, context, skip_style_tags)
  File "/Users/quentinlhoest/.virtualenvs/hf-transformers/lib/python3.7/site-packages/mwparserfromhell/parser/__init__.py", line 93, in parse
    tokens = self._tokenizer.tokenize(text, context, skip_style_tags)
mwparserfromhell.parser.ParserError: This is a bug and should be reported. Info: C tokenizer exited with non-empty token stack.
```

Thank you in advance !

**Comment by earwig** [comment]
This bug was already fixed in master. I'll publish a release (soon).

**Comment by lhoestq** [comment]
Thanks !
